### ISSUE TITLE
Don't replace Contributor tag.

### ISSUE THREAD

**Issue by micwoj92** [bence98/cpan2aur2git#2]
Current contributor should be put on top and old contributor retained.
https://aur.archlinux.org/cgit/aur.git/commit/?h=perl-datetimex-easy&id=76218c99d023a5b4cad3cb14f0e17656a3a254d9

**Comment by bence98** [comment]
Unfortunately, `cpan2aur` cannot do that, in fact, when it is being run, the AUR repo is not even cloned yet. Plus, since it always overwrites PKGBUILD, it never uses anything from the previous Contributor's/Maintainer's PKGBUILD, everything it generates is its *original work*. Which is often a good thing, as a lot of packages that CpanBot took over had the old `cpan2aur`-style `build()`/`package()`, old dependencies that were removed upstream but not from AUR, stale `.SRCINFO` etc. (or even that obnoxious paranoid-scrambled e-mail address you linked).
However, in some cases it could be beneficial to take i.e. `optdepends` from a previous PKGBUILD. *If* I ever do that, I'll be sure to credit the original creators.
However, as for now, it would be way too much work trying to auto-merge the old and new PKGBUILD, so I just replace it with a fully fresh one.
